from ..dtypes.factory import BaseFactory

DOCTYPE = BaseFactory.create_not_recordable_tag_class('!DOCTYPE html', False)
HTML = BaseFactory.create_not_recordable_tag_class('html', True)
HEAD = BaseFactory.create_not_recordable_tag_class('head', True)
BODY = BaseFactory.create_not_recordable_tag_class('body', True)
TITLE = BaseFactory.create_head_tag_class('title', True)
H1 = BaseFactory.create_body_tag_class('h1', True)
H2 = BaseFactory.create_body_tag_class('h2', True)
H3 = BaseFactory.create_body_tag_class('h3', True)
H4 = BaseFactory.create_body_tag_class('h4', True)
H5 = BaseFactory.create_body_tag_class('h5', True)
H6 = BaseFactory.create_body_tag_class('h6', True)
P = BaseFactory.create_body_tag_class('p', True)
BR = BaseFactory.create_body_tag_class('br', False)
HR = BaseFactory.create_body_tag_class('hr', False)
